### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by NightFury10497** [anicolson/bidirectional_2018#1]
Can it do Speaker Identification?
If yes please tell some steps

**Comment by anicolson** [comment]
It can be used for speech separation for a speaker identification system, or it can be used to identify missing features for a missing feature-based speaker identification system. See this work for a missing feature-based speaker identification system:

https://maxwell.ict.griffith.edu.au/spl/publications/papers/icsps17_aaron.pdf

you would have to use the magnitude spectrum as the input feature to the speaker models.
